<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WatchLater extends Model
{
    public function __set($key, $value)
    {
        parent::__set($key, $value); // TODO: Change the autogenerated stub
    }
}
